// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2adRPXz4mEmAwHTTyvyuo6uBSSfv-wQ',
    appId: '1:711475016941:web:89b4da75c46995cb2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    authDomain: 'mm8888-244371.firebaseapp.com',
    storageBucket: 'mm8888-244371.appspot.com',
    measurementId: 'G-NK8EKC88TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6PEeuB_zyMfyU5kYd7XuOO3059MLbM4',
    appId: '1:711475016941:android:e01c00eba2dc9ced2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMKXeqlpCOpuCaTX3582NI2YOstqjAPpQ',
    appId: '1:711475016941:ios:413898909393fd9d2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
    iosClientId: '711475016941-ehiqrt52qgf3aklmkjl9gutkj3b7d2rc.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.mm8888',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMKXeqlpCOpuCaTX3582NI2YOstqjAPpQ',
    appId: '1:711475016941:ios:413898909393fd9d2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
    iosClientId: '711475016941-ehiqrt52qgf3aklmkjl9gutkj3b7d2rc.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.mm8888',
  );
}
