// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAznifNBq8pVV7_ksUHYoB8CA8q4YYtjXQ',
    appId: '1:711475016941:web:5d8e82c7f25348ac2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    authDomain: 'mm8888-244371.firebaseapp.com',
    storageBucket: 'mm8888-244371.appspot.com',
    measurementId: 'G-BQ00SES3V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1iybZaySfLqIGtN6sOMcQZy2izx4g3Zs',
    appId: '1:711475016941:android:baa4bd23ccdb77de2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hqLfsNaiAdJdLBGz9q3oF949vM-T1dA',
    appId: '1:711475016941:ios:aa5c92389058a99e2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
    iosClientId: '711475016941-jfolfsmiidg5ajnqtdbllv54q7frh6hs.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.mm8888.mm8888',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hqLfsNaiAdJdLBGz9q3oF949vM-T1dA',
    appId: '1:711475016941:ios:aa5c92389058a99e2888e4',
    messagingSenderId: '711475016941',
    projectId: 'mm8888-244371',
    storageBucket: 'mm8888-244371.appspot.com',
    iosClientId: '711475016941-jfolfsmiidg5ajnqtdbllv54q7frh6hs.apps.googleusercontent.com',
    iosBundleId: 'com.fx712.mm8888.mm8888',
  );
}
